name = "rumahweb"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "rumahweb.elbarputra.my.id"
custom_domain = true
[[routes]]
pattern = "npca.netflix.com.rumahweb.elbarputra.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.rumahweb.elbarputra.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.rumahweb.elbarputra.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.rumahweb.elbarputra.my.id"
custom_domain = true
[[routes]]
pattern = "blog.ruangguru.com.rumahweb.elbarputra.my.id"
custom_domain = true

[vars]
PROXYIP = "203.194.112.119:8443"
UUID = "8025fa8a-3ecd-4984-93a6-9aa0f0b01378"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
